apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2024-07-23T12:44:45Z'
  generation: 2
  labels:
    project: infrastructure
    source: internal
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:controllerNamespace: {}
          f:health:
            f:status: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-07-23T12:44:50Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:project: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:path: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2024-07-23T12:45:20Z'
  name: elastic-stack
  namespace: argocd
  resourceVersion: '239065'
  uid: 04f219fd-5b2b-4cfd-9dbe-d08fe217bff0
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/elastic-stack
status:
  controllerNamespace: argocd
  health:
    status: Missing
  reconciledAt: '2024-07-23T12:44:45Z'
  resources:
    - health:
        status: Missing
      kind: PersistentVolumeClaim
      name: nfs-backup-elastic
      namespace: elastic-stack
      status: OutOfSync
      version: v1
    - health:
        status: Missing
      kind: Service
      name: elasticsearch
      namespace: elastic-stack
      status: OutOfSync
      version: v1
    - group: apps
      health:
        status: Missing
      kind: StatefulSet
      name: elasticsearch-cluster
      namespace: elastic-stack
      status: OutOfSync
      version: v1
    - group: networking.k8s.io
      health:
        status: Missing
      kind: Ingress
      name: elasticsearch-ingress
      namespace: elastic-stack
      status: OutOfSync
      version: v1
  sourceType: Kustomize
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: elastic-stack
        server: https://kubernetes.default.svc
      source:
        path: argocd/sources/elastic-stack
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
    revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
    status: OutOfSync
spec:
  destination:
    namespace: elastic-stack
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: argocd/sources/elastic-stack
    repoURL: git@github.com:Binesty/Automation.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
