apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2024-07-23T11:51:10Z'
  generation: 1657
  labels:
    project: infrastructure
    source: internal
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:project: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:path: {}
            f:repoURL: {}
            f:targetRevision: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2024-07-23T12:26:42Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:controllerNamespace: {}
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncStrategy:
                  .: {}
                  f:hook: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:externalURLs: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:server: {}
              f:source:
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-10-03T14:54:36Z'
  name: ingress
  namespace: argocd
  resourceVersion: '2132096'
  uid: 383840e9-3aa7-40e6-b446-4eb2a47c99f8
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/ingress
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2024-07-23T11:58:58Z'
      deployedAt: '2024-07-23T11:59:11Z'
      id: 0
      initiatedBy:
        username: admin
      revision: 2261fa003c30651487a5b17d55126af95ba015d4
      source:
        path: argocd/sources/ingress
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
    - deployStartedAt: '2024-07-23T12:23:50Z'
      deployedAt: '2024-07-23T12:23:53Z'
      id: 1
      initiatedBy:
        username: admin
      revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
      source:
        path: argocd/sources/ingress
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
    - deployStartedAt: '2024-07-23T12:24:39Z'
      deployedAt: '2024-07-23T12:24:40Z'
      id: 2
      initiatedBy:
        username: admin
      revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
      source:
        path: argocd/sources/ingress
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
    - deployStartedAt: '2024-07-23T12:26:42Z'
      deployedAt: '2024-07-23T12:26:43Z'
      id: 3
      initiatedBy:
        username: admin
      revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
      source:
        path: argocd/sources/ingress
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
  operationState:
    finishedAt: '2024-07-23T12:26:43Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: '2024-07-23T12:26:42Z'
    syncResult:
      resources:
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/argocd-server-ingress unchanged
          name: argocd-server-ingress
          namespace: argocd
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/kafka-ui-ingress unchanged
          name: kafka-ui-ingress
          namespace: kafka
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/keycloak-ingress unchanged
          name: keycloak-ingress
          namespace: keycloak
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/minio-ingress unchanged
          name: minio-ingress
          namespace: minio
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/vault-ingress unchanged
          name: vault-ingress
          namespace: vault
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/longhorn-ingress unchanged
          name: longhorn-ingress
          namespace: longhorn-system
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/grafana-ingress unchanged
          name: grafana-ingress
          namespace: monitoring
          status: Synced
          syncPhase: Sync
          version: v1
      revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
      source:
        path: argocd/sources/ingress
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
  reconciledAt: '2024-10-03T14:54:35Z'
  resources:
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: argocd-server-ingress
      namespace: argocd
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: kafka-ui-ingress
      namespace: kafka
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: keycloak-ingress
      namespace: keycloak
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: longhorn-ingress
      namespace: longhorn-system
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: minio-ingress
      namespace: minio
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: grafana-ingress
      namespace: monitoring
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: vault-ingress
      namespace: vault
      status: Synced
      version: v1
  sourceType: Directory
  summary:
    externalURLs:
      - https://argocd.binesty.io/
      - https://grafana.binesty.io/
      - https://kafka.binesty.io/
      - https://keycloak.binesty.io/
      - https://longhorn.binesty.io/
      - https://minio.binesty.io/
      - https://vault.binesty.io/
  sync:
    comparedTo:
      destination:
        server: https://kubernetes.default.svc
      source:
        path: argocd/sources/ingress
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
    revision: b7502173803aa4b39bfa80cbf636b252e35012e1
    status: Synced
spec:
  destination:
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: argocd/sources/ingress
    repoURL: git@github.com:Binesty/Automation.git
    targetRevision: main
