apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"creationTimestamp":"2024-06-05T20:58:07Z","generation":7483,"labels":{"project":"infrastructure","source":"internal"},"managedFields":[{"apiVersion":"argoproj.io/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:project":{},"f:source":{}}},"f:spec":{".":{},"f:destination":{".":{},"f:namespace":{},"f:server":{}},"f:project":{},"f:source":{".":{},"f:targetRevision":{}}},"f:status":{".":{},"f:controllerNamespace":{},"f:health":{".":{},"f:status":{}},"f:summary":{},"f:sync":{".":{},"f:comparedTo":{".":{},"f:destination":{".":{},"f:namespace":{},"f:server":{}},"f:source":{".":{},"f:targetRevision":{}}}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2024-06-05T20:58:07Z"},{"apiVersion":"argoproj.io/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:source":{"f:path":{},"f:repoURL":{}}}},"manager":"argocd-server","operation":"Update","time":"2024-07-19T14:51:17Z"},{"apiVersion":"argoproj.io/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:history":{},"f:operationState":{".":{},"f:finishedAt":{},"f:message":{},"f:operation":{".":{},"f:initiatedBy":{".":{},"f:username":{}},"f:retry":{},"f:sync":{".":{},"f:revision":{},"f:syncStrategy":{".":{},"f:hook":{}}}},"f:phase":{},"f:startedAt":{},"f:syncResult":{".":{},"f:resources":{},"f:revision":{},"f:source":{".":{},"f:path":{},"f:repoURL":{},"f:targetRevision":{}}}},"f:reconciledAt":{},"f:resources":{},"f:sourceType":{},"f:sync":{"f:comparedTo":{"f:source":{"f:path":{},"f:repoURL":{}}},"f:revision":{},"f:status":{}}}},"manager":"argocd-application-controller","operation":"Update","time":"2024-07-19T16:52:17Z"}],"name":"issuers","namespace":"argocd","resourceVersion":"17435443","selfLink":"/apis/argoproj.io/v1alpha1/namespaces/argocd/applications/issuers","uid":"248a963d-d5b9-4d46-9f41-72daf394da6f"},"spec":{"destination":{"namespace":"cert-manager","server":"https://kubernetes.default.svc"},"project":"infrastructure","source":{"path":"argocd/sources/issuers","repoURL":"git@github.com:Binesty/Automation.git","targetRevision":"main"}},"status":{"controllerNamespace":"argocd","health":{"status":"Healthy"},"history":[{"deployStartedAt":"2024-05-15T19:12:32Z","deployedAt":"2024-05-15T19:12:33Z","id":0,"initiatedBy":{},"revision":"745da0e6100d4f7c9879c693e513bf07f41e9280","source":{"path":"cluster/argocd/sources/issuers","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}},{"deployStartedAt":"2024-05-15T19:41:59Z","deployedAt":"2024-05-15T19:42:04Z","id":1,"initiatedBy":{},"revision":"a6ecca005f0eb99c92d6c80993fa0062373c8107","source":{"path":"cluster/argocd/sources/issuers","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}},{"deployStartedAt":"2024-06-12T18:25:40Z","deployedAt":"2024-06-12T18:25:44Z","id":2,"initiatedBy":{"username":"admin"},"revision":"8bd85f8c635d34c1072a2aa85667bbb0c4bac4f6","source":{"path":"cluster/argocd/sources/issuers","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}}],"operationState":{"finishedAt":"2024-06-12T18:25:44Z","message":"successfully
      synced (all tasks
      run)","operation":{"initiatedBy":{"username":"admin"},"retry":{},"sync":{"revision":"8bd85f8c635d34c1072a2aa85667bbb0c4bac4f6","syncStrategy":{"hook":{}}}},"phase":"Succeeded","startedAt":"2024-06-12T18:25:40Z","syncResult":{"resources":[{"group":"cert-manager.io","hookPhase":"Running","kind":"ClusterIssuer","message":"clusterissuer.cert-manager.io/selfsigned-issuer
      configured","name":"selfsigned-issuer","namespace":"cert-manager","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"cert-manager.io","hookPhase":"Running","kind":"ClusterIssuer","message":"clusterissuer.cert-manager.io/binesty-ca-issuer
      configured","name":"binesty-ca-issuer","namespace":"cert-manager","status":"Synced","syncPhase":"Sync","version":"v1"}],"revision":"8bd85f8c635d34c1072a2aa85667bbb0c4bac4f6","source":{"path":"cluster/argocd/sources/issuers","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}}},"reconciledAt":"2024-07-19T16:52:17Z","resources":[{"group":"cert-manager.io","health":{"message":"Signing
      CA
      verified","status":"Healthy"},"kind":"ClusterIssuer","name":"binesty-ca-issuer","status":"Synced","version":"v1"},{"group":"cert-manager.io","health":{"status":"Healthy"},"kind":"ClusterIssuer","name":"selfsigned-issuer","status":"Synced","version":"v1"}],"sourceType":"Kustomize","summary":{},"sync":{"comparedTo":{"destination":{"namespace":"cert-manager","server":"https://kubernetes.default.svc"},"source":{"path":"argocd/sources/issuers","repoURL":"git@github.com:Binesty/Automation.git","targetRevision":"main"}},"revision":"2325df6152c42fe82976edd3eff16d40c0d39366","status":"Synced"}}}
  creationTimestamp: '2024-07-22T14:51:11Z'
  generation: 190
  labels:
    project: infrastructure
    source: internal
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:project: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:path: {}
            f:repoURL: {}
            f:targetRevision: {}
        f:status:
          .: {}
          f:controllerNamespace: {}
          f:health:
            .: {}
            f:status: {}
          f:sourceType: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination:
                .: {}
                f:namespace: {}
                f:server: {}
              f:source:
                .: {}
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2024-07-22T14:51:11Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncStrategy:
                  .: {}
                  f:hook: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sync:
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-07-23T12:30:57Z'
  name: issuers
  namespace: argocd
  resourceVersion: '233460'
  uid: 82d33704-ba96-4eb9-93db-6c8b43e34acd
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/issuers
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2024-05-15T19:12:32Z'
      deployedAt: '2024-05-15T19:12:33Z'
      id: 0
      initiatedBy: {}
      revision: 745da0e6100d4f7c9879c693e513bf07f41e9280
      source:
        path: cluster/argocd/sources/issuers
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-05-15T19:41:59Z'
      deployedAt: '2024-05-15T19:42:04Z'
      id: 1
      initiatedBy: {}
      revision: a6ecca005f0eb99c92d6c80993fa0062373c8107
      source:
        path: cluster/argocd/sources/issuers
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-06-12T18:25:40Z'
      deployedAt: '2024-06-12T18:25:44Z'
      id: 2
      initiatedBy:
        username: admin
      revision: 8bd85f8c635d34c1072a2aa85667bbb0c4bac4f6
      source:
        path: cluster/argocd/sources/issuers
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-07-22T18:40:07Z'
      deployedAt: '2024-07-22T18:40:09Z'
      id: 3
      initiatedBy:
        username: admin
      revision: 2261fa003c30651487a5b17d55126af95ba015d4
      source:
        path: argocd/sources/issuers
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
  operationState:
    finishedAt: '2024-07-22T18:40:09Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 2261fa003c30651487a5b17d55126af95ba015d4
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: '2024-07-22T18:40:07Z'
    syncResult:
      resources:
        - group: cert-manager.io
          hookPhase: Running
          kind: ClusterIssuer
          message: clusterissuer.cert-manager.io/binesty-ca-issuer created
          name: binesty-ca-issuer
          namespace: cert-manager
          status: Synced
          syncPhase: Sync
          version: v1
        - group: cert-manager.io
          hookPhase: Running
          kind: ClusterIssuer
          message: clusterissuer.cert-manager.io/selfsigned-issuer created
          name: selfsigned-issuer
          namespace: cert-manager
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 2261fa003c30651487a5b17d55126af95ba015d4
      source:
        path: argocd/sources/issuers
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
  reconciledAt: '2024-07-23T12:30:57Z'
  resources:
    - group: cert-manager.io
      health:
        message: Signing CA verified
        status: Healthy
      kind: ClusterIssuer
      name: binesty-ca-issuer
      status: Synced
      version: v1
    - group: cert-manager.io
      health:
        status: Healthy
      kind: ClusterIssuer
      name: selfsigned-issuer
      status: Synced
      version: v1
  sourceType: Kustomize
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: cert-manager
        server: https://kubernetes.default.svc
      source:
        path: argocd/sources/issuers
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
    revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
    status: Synced
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: argocd/sources/issuers
    repoURL: git@github.com:Binesty/Automation.git
    targetRevision: main
