apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2024-07-23T16:29:00Z'
  generation: 13
  labels:
    project: infrastructure
    source: external
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:project: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:chart: {}
            f:repoURL: {}
            f:targetRevision: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2024-07-23T16:30:09Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:controllerNamespace: {}
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncStrategy:
                  .: {}
                  f:hook: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:chart: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:chart: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-07-23T16:31:30Z'
  name: loki
  namespace: argocd
  resourceVersion: '321706'
  uid: b9d4140b-1248-491c-879c-87d7f8528bf8
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/loki
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2024-07-23T16:30:09Z'
      deployedAt: '2024-07-23T16:30:10Z'
      id: 0
      initiatedBy:
        username: admin
      revision: 2.10.2
      source:
        chart: loki-stack
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 2.10.2
  operationState:
    finishedAt: '2024-07-23T16:30:11Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 2.10.2
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: '2024-07-23T16:30:09Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/loki created
          name: loki
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/loki-promtail created
          name: loki-promtail
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Secret
          message: secret/loki-promtail created
          name: loki-promtail
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Secret
          message: secret/loki created
          name: loki
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: configmap/loki-loki-stack-test created
          name: loki-loki-stack-test
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: configmap/loki-loki-stack created
          name: loki-loki-stack
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: ClusterRole
          message: "clusterrole.rbac.authorization.k8s.io/loki-promtail reconciled. reconciliation required create\n\tmissing rules added:\n\t\t{Verbs:[get watch list] APIGroups:[] Resources:[nodes nodes/proxy services endpoints pods] ResourceNames:[] NonResourceURLs:[]}. clusterrole.rbac.authorization.k8s.io/loki-promtail configured. Warning: resource clusterroles/loki-promtail is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically."
          name: loki-promtail
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: ClusterRoleBinding
          message: "clusterrolebinding.rbac.authorization.k8s.io/loki-promtail reconciled. reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount APIGroup: Name:loki-promtail Namespace:observability}. clusterrolebinding.rbac.authorization.k8s.io/loki-promtail configured. Warning: resource clusterrolebindings/loki-promtail is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically."
          name: loki-promtail
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: Role
          message: "role.rbac.authorization.k8s.io/loki reconciled. reconciliation required create\n\tmissing rules added:\n\t\t{Verbs:[use] APIGroups:[extensions] Resources:[podsecuritypolicies] ResourceNames:[loki] NonResourceURLs:[]}. role.rbac.authorization.k8s.io/loki configured. Warning: resource roles/loki is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically."
          name: loki
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: RoleBinding
          message: "rolebinding.rbac.authorization.k8s.io/loki reconciled. reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount APIGroup: Name:loki Namespace:}. rolebinding.rbac.authorization.k8s.io/loki configured. Warning: resource rolebindings/loki is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically."
          name: loki
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/loki-headless created
          name: loki-headless
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/loki-memberlist created
          name: loki-memberlist
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/loki created
          name: loki
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: DaemonSet
          message: daemonset.apps/loki-promtail created
          name: loki-promtail
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: statefulset.apps/loki created
          name: loki
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 2.10.2
      source:
        chart: loki-stack
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 2.10.2
  reconciledAt: '2024-07-23T16:30:11Z'
  resources:
    - kind: ConfigMap
      name: loki-loki-stack
      namespace: observability
      status: Synced
      version: v1
    - kind: ConfigMap
      name: loki-loki-stack-test
      namespace: observability
      status: Synced
      version: v1
    - kind: Secret
      name: loki
      namespace: observability
      status: Synced
      version: v1
    - kind: Secret
      name: loki-promtail
      namespace: observability
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: loki
      namespace: observability
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: loki-headless
      namespace: observability
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: loki-memberlist
      namespace: observability
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: loki
      namespace: observability
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: loki-promtail
      namespace: observability
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: DaemonSet
      name: loki-promtail
      namespace: observability
      status: Synced
      version: v1
    - group: apps
      health:
        message: >-
          statefulset rolling update complete 1 pods at revision
          loki-655c6d66f4...
        status: Healthy
      kind: StatefulSet
      name: loki
      namespace: observability
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: loki-promtail
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: loki-promtail
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: Role
      name: loki
      namespace: observability
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: loki
      namespace: observability
      status: Synced
      version: v1
  sourceType: Helm
  summary:
    images:
      - docker.io/grafana/promtail:2.9.3
      - grafana/loki:2.6.1
  sync:
    comparedTo:
      destination:
        namespace: observability
        server: https://kubernetes.default.svc
      source:
        chart: loki-stack
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 2.10.2
    revision: 2.10.2
    status: Synced
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
