apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2024-07-23T16:37:14Z'
  generation: 9
  labels:
    project: infrastructure
    source: external
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:project: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:chart: {}
            f:repoURL: {}
            f:targetRevision: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2024-07-23T16:38:11Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:controllerNamespace: {}
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncStrategy:
                  .: {}
                  f:hook: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:chart: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:chart: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-07-23T16:38:20Z'
  name: tempo
  namespace: argocd
  resourceVersion: '324227'
  uid: df5f1c8e-8723-4456-8dfe-a3e27a9b0923
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/tempo
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2024-07-23T16:38:11Z'
      deployedAt: '2024-07-23T16:38:12Z'
      id: 0
      initiatedBy:
        username: admin
      revision: 1.10.1
      source:
        chart: tempo
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 1.10.1
  operationState:
    finishedAt: '2024-07-23T16:38:12Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 1.10.1
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: '2024-07-23T16:38:11Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/tempo created
          name: tempo
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: configmap/tempo created
          name: tempo
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/tempo created
          name: tempo
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: statefulset.apps/tempo created
          name: tempo
          namespace: observability
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 1.10.1
      source:
        chart: tempo
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 1.10.1
  reconciledAt: '2024-07-23T16:38:12Z'
  resources:
    - kind: ConfigMap
      name: tempo
      namespace: observability
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: tempo
      namespace: observability
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: tempo
      namespace: observability
      status: Synced
      version: v1
    - group: apps
      health:
        message: >-
          statefulset rolling update complete 1 pods at revision
          tempo-6598756c6d...
        status: Healthy
      kind: StatefulSet
      name: tempo
      namespace: observability
      status: Synced
      version: v1
  sourceType: Helm
  summary:
    images:
      - grafana/tempo:2.5.0
  sync:
    comparedTo:
      destination:
        namespace: observability
        server: https://kubernetes.default.svc
      source:
        chart: tempo
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 1.10.1
    revision: 1.10.1
    status: Synced
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.10.1
