apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2024-07-22T19:26:35Z'
  generation: 382
  labels:
    project: infrastructure
    source: internal
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:project: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:path: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2024-07-23T12:28:38Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:controllerNamespace: {}
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:resources: {}
                f:revision: {}
                f:syncOptions: {}
                f:syncStrategy:
                  .: {}
                  f:hook: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:revision: {}
              f:source:
                .: {}
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-07-23T12:42:29Z'
  name: vault
  namespace: argocd
  resourceVersion: '237993'
  uid: 4381d4f5-8684-4f80-8bcc-5eb0a788f9f7
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/vault
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2024-07-22T19:26:48Z'
      deployedAt: '2024-07-22T19:26:50Z'
      id: 0
      initiatedBy:
        username: admin
      revision: 2261fa003c30651487a5b17d55126af95ba015d4
      source:
        path: argocd/sources/vault
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
    - deployStartedAt: '2024-07-23T12:23:39Z'
      deployedAt: '2024-07-23T12:23:43Z'
      id: 1
      initiatedBy:
        username: admin
      revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
      source:
        path: argocd/sources/vault
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
    - deployStartedAt: '2024-07-23T12:24:24Z'
      deployedAt: '2024-07-23T12:24:25Z'
      id: 2
      initiatedBy:
        username: admin
      revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
      source:
        path: argocd/sources/vault
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
  operationState:
    finishedAt: '2024-07-23T12:25:06Z'
    message: successfully synced (no more tasks)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        resources:
          - group: networking.k8s.io
            kind: Ingress
            name: vault-ingress
            namespace: vault
        revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: '2024-07-23T12:25:06Z'
    syncResult:
      revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
      source:
        path: argocd/sources/vault
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
  reconciledAt: '2024-07-23T12:41:08Z'
  resources:
    - kind: ConfigMap
      name: vault-config
      namespace: vault
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: vault
      namespace: vault
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: vault-agent-injector-svc
      namespace: vault
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: vault-internal
      namespace: vault
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: vault-ui
      namespace: vault
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: vault
      namespace: vault
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: vault-agent-injector
      namespace: vault
      status: Synced
      version: v1
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: Deployment
      name: vault-agent-injector
      namespace: vault
      status: Synced
      version: v1
    - group: apps
      health:
        message: statefulset has 1 ready pods
        status: Healthy
      kind: StatefulSet
      name: vault
      namespace: vault
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: vault-agent-injector-clusterrole
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: vault-agent-injector-binding
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: vault-server-binding
      status: Synced
      version: v1
  sourceType: Kustomize
  summary:
    images:
      - hashicorp/vault-k8s:1.4.1
      - hashicorp/vault:1.16.1
  sync:
    comparedTo:
      destination:
        namespace: vault
        server: https://kubernetes.default.svc
      source:
        path: argocd/sources/vault
        repoURL: git@github.com:Binesty/Automation.git
        targetRevision: main
    revision: e5d794e616b52162b76b97d41c8ca39fd6f171f2
    status: Synced
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: argocd/sources/vault
    repoURL: git@github.com:Binesty/Automation.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
